unique_ids:
  assets:
    iconfinder_telegram_3246742.png: RDVEYYDEZIPVLBAUGAUYNAFZZZBQ5XVY
    standard-page.html: HYPRX4VDOZLOCIZJ4BVJA3ABFZLNUHZ4
    theme.css: ZLDR4EBKS46GQWBA64MMDN7E2KZBPFH2
  forms:
    Form1: NLF2AWUOVXMW327YSEMYJR24YEWHR67C
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: BRI2VIXCREBJWHW7KESXLHI5Q4HIW6JT
